### ISSUE TITLE
New Test to GitReminder

### ISSUE THREAD

**Issue by LBeckX** [LBeckX/GitReminder-Tester#16]
Test

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckx mail lb@1601.com

**Comment by gh-lb1601com** [comment]
Can't assign this user, cause I did not find it this repo :(

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckx mail dev@1601.com

**Comment by gh-lb1601com** [comment]
Can't assign this user, cause I did not find it this repo :(

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @gittrigger-lb mail dev@1601.com

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckx mail dev@1601.com

**Comment by gh-lb1601com** [comment]
Can't assign this user, cause I did not find it this repo :(

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckx mail dev@1601.com

**Comment by gh-lb1601com** [comment]
Can't assign this user, cause I did not find it this repo :(

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckx

**Comment by gh-lb1601com** [comment]
Can't assign this user, cause I did not find it this repo :(

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckX

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckx

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @gittrigger-lb

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckx

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @gittrigger-lb comment hello world!

**Comment by gh-lb1601com** [comment]
hello world!

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckx

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @gh-lb1601com mail lb@1601.com

**Comment by LBeckX** [comment]
@gh-lb1601com 0d @LBeckX mail lb@1601.com
