### ISSUE TITLE
Test #10 To GitReminder (Wrong Time +365d)

### ISSUE THREAD

**Issue by LBeckX** [LBeckX/GitReminder-Tester#26]
@gh-lb1601com +500d @LBeckX

**Comment by gh-lb1601com** [comment]
It is not possible to assign a user in more than 365 days! One year is max! :(

**Comment by LBeckX** [comment]
@gh-lb1601com +500d @ADoebeling

**Comment by gh-lb1601com** [comment]
It is not possible to assign a user in more than 365 days! One year is max! :(

**Comment by LBeckX** [comment]
@gh-lb1601com 90000000m @gittrigger-lb

**Comment by gh-lb1601com** [comment]
It is not possible to assign a user in more than 365 days! One year is max! :(

**Comment by LBeckX** [comment]
Done!

**Comment by gh-lb1601com** [comment]
It is not possible to assign a user in more than 365 days! One year is max! :(
