### ISSUE TITLE
Test #13 To GitReminder (Comment Link)

### ISSUE THREAD

**Issue by LBeckX** [LBeckX/GitReminder-Tester#30]
@gh-lb1601com 0d @lbeckx comment https://www.google.de/?gfe_rd=cr&ei=JFSGV9bKPOqv8weC4LHQAQ

**Comment by gh-lb1601com** [comment]
https://www.google.de/?gfe_rd=cr&ei=JFSGV9bKPOqv8weC4LHQAQ

**Comment by LBeckX** [comment]
Done!
